// Order Creation
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

// Order Details
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// My Orders List
export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ADMIN_ORDERS_REQUEST = 'ADMIN_ORDERS_REQUEST';
export const ADMIN_ORDERS_SUCCESS = 'ADMIN_ORDERS_SUCCESS';
export const ADMIN_ORDERS_FAIL = 'ADMIN_ORDERS_FAIL';

export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST';
export const ORDER_UPDATE_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS';
export const ORDER_UPDATE_STATUS_FAIL = 'ORDER_UPDATE_STATUS_FAIL';
export const ORDER_UPDATE_STATUS_RESET = 'ORDER_UPDATE_STATUS_RESET';

export const GET_TOP_PRODUCTS_REQUEST = 'GET_TOP_PRODUCTS_REQUEST';
export const GET_TOP_PRODUCTS_SUCCESS = 'GET_TOP_PRODUCTS_SUCCESS';
export const GET_TOP_PRODUCTS_FAIL = 'GET_TOP_PRODUCTS_FAIL';